name: 构建并发布Docker镜像

on:
  push:
    branches: [main]
  workflow_dispatch:

# 全局权限设置
permissions:
  packages: write
  contents: write

jobs:
  docker:
    name: 构建Docker镜像
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置QEMU
        uses: docker/setup-qemu-action@v2

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 登录到GitHub容器注册表
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 提取元数据
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/Fluid_Docker
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: 构建并推送
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
